//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RitaOfficeTool {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Rita : global::System.Configuration.ApplicationSettingsBase {
        
        private static Rita defaultInstance = ((Rita)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Rita())));
        
        public static Rita Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("年末余额|本年发生数|2022-12-31")]
        public string old_sub_str {
            get {
                return ((string)(this["old_sub_str"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("年初余额|上年发生数|2021-12-31")]
        public string new_sub_str {
            get {
                return ((string)(this["new_sub_str"]));
            }
            set {
                this["new_sub_str"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("本期减少|本年减少|减：")]
        public string negative_number_str {
            get {
                return ((string)(this["negative_number_str"]));
            }
            set {
                this["negative_number_str"] = value;
            }
        }
    }
}
